function SelectNodesAPDL(XYZ,Tol,Folder)
% 
% SelectNodesAPDL(XYZ,Tol,Folder)
% 
% Created By:
%   Mateo G. H. (2021/06/12)

%%%%%%%%%%%%%%%%%%%%%%%%%% ------------------------------------------------
%%% Generate APDL Code %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%
NodesNum = size(XYZ,1);
Text = [...
    '! ----------------------',newline,...
    '! --- Node selection ---',newline,...
    '! ----------------------',newline,...
    newline,...
    'ALLSEL',newline,...
    'FINISH',newline,...
    '/PREP7',newline,...
    '_NNODES = ',num2str(NodesNum,'%.0f'),newline,...
    newline,...
    '*DIM,  _PhiNodeID,ARRAY,',num2str(NodesNum,'%.0f'),',1',newline,...
    ];
for Count_Nodes = 1:NodesNum
    Text = [...
        Text,newline,...
        '! --- N,',num2str(Count_Nodes,'%.0f'),':',newline,...
        'ALLSEL',newline,...
        'NSEL,  S,LOC,Y',num2str(XYZ(Count_Nodes,2)+[-Tol,Tol],',%f'),newline,...
        'NSEL,  R,LOC,Z',num2str(XYZ(Count_Nodes,3)+[-Tol,Tol],',%f'),newline,...
        'NSEL,  R,LOC,X',num2str(XYZ(Count_Nodes,1)+[-Tol,Tol],',%f'),newline,...
        '*GET,  _COUNTNODE_',num2str(Count_Nodes,'%.0f'),',NODE,0,COUNT',newline,...
        '*DIM,  _LISTN_',num2str(Count_Nodes,'%.0f'),',ARRAY,_COUNTNODE_',num2str(Count_Nodes,'%.0f'),',1',newline,...
        '*VGET, _LISTN_',num2str(Count_Nodes,'%.0f'),',NODE,,NLIST',newline,...
        '_PhiNodeID(',num2str(Count_Nodes,'%.0f'),')  = _LISTN_',num2str(Count_Nodes,'%.0f'),'(1)',newline,...
        newline,...
        ]; %#ok<*AGROW>
end

%%%%%%%%%%%%%%%%% ---------------------------------------------------------
%%% Save File %%%
%%%%%%%%%%%%%%%%%
cd(Folder);
FID = fopen('SelectNodes_APDL.inp','w');
if FID == -1, error('Cannot open file %s', FileName); end
fwrite(FID,Text,'char');
fclose(FID);
end
